name: Build Wasm
on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      EMCC_CFLAGS: |
        -O3
        -o ./public/increment.js
        -s EXPORTED_FUNCTIONS=['_increment']
        -s EXPORTED_RUNTIME_METHODS=ccall

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11

      - name: Setup cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
          targets: wasm32-unknown-emscripten

      - name: Fmt
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy -- --deny warnings

      - name: Test
        run: cargo test

      - name: Build tree-sitter-json
        run: cargo build --package tree-sitter-json --target wasm32-unknown-emscripten --release
        env:
          EMCC_CFLAGS: -O3

      - name: Build My Library
        run: cargo build --target wasm32-unknown-emscripten --release
        env:
          EMCC_CFLAGS: |
            -O3
            -o ./public/increment.js
            -s EXPORTED_FUNCTIONS=['_increment','_get_json_cst','_free_string']
            -s EXPORTED_RUNTIME_METHODS=ccall

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
