name: Build Wasm
on: [push]
jobs:
  build:
    env:
      EMCC_CFLAGS: |
        -O3
        -o ./increment.js
        -s EXPORTED_FUNCTIONS=['_increment']
        -s EXPORTED_RUNTIME_METHODS=ccall

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11

      - name: Setup cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-emscripten

      - name: Build
        run: cargo build --target wasm32-unknown-emscripten --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            output/increment.js
            output/increment.wasm
